-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/ldap.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ldap_domains (
  domain_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  domain BLOB NOT NULL, user_id INTEGER NOT NULL
);

CREATE INDEX user_id ON /*_*/ldap_domains (user_id);
